services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cal_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  json-server:
    image: node:20-alpine
    container_name: cal_json_server_dev
    volumes:
      - .:/data
    working_dir: /data
    command: sh -c "npx json-server sportData.json"
    ports:
      - "3000:3000"
